### ISSUE TITLE
Investigate tensorboardX-like package.

### ISSUE THREAD

**Issue by stites** [hasktorch/hasktorch#101]
More specific version of #56, aiming for the lowest-hanging fruit of integrating with tensorboard by mimicking [tensorboardX](https://github.com/lanpa/tensorboard-pytorch). Preemptively assigned to @xilnocas (but I can take it off of your plate if you are overloaded).

Here is the main module to implement: [tensorboardX/writer.py](https://github.com/lanpa/tensorboardX/blob/master/tensorboardX/writer.py)
Here is the tensorflow/haskell logging system we might be able to piggy-back off of: [tensorflow-logging](https://github.com/tensorflow/haskell/blob/master/tensorflow-logging/src/TensorFlow/Logging.hs)

**Comment by austinvhuang** [comment]
Will close this for now to prioritise release critical issues, can revisit if someone wants to pick it up.
