### ISSUE TITLE
MNIST example

### ISSUE THREAD

**Issue by stites** [hasktorch/hasktorch#102]
A good place to start getting familiar with the API that doesn't require access to a GPU (unlike #64) is porting the MNIST example from [pytorch/examples](https://github.com/pytorch/examples/blob/master/mnist/main.py) and doing a small write-up. [All](https://github.com/tensorflow/haskell/blob/master/tensorflow-mnist/app/Main.hs) the [other](https://github.com/mstksg/backprop/blob/master/renders/backprop-mnist.pdf) haskell [libraries](https://github.com/HuwCampbell/grenade/blob/master/examples/main/mnist.hs) are doing it and everyone [loves](http://www-cs-students.stanford.edu/~blynn/haskell/brain.html) writing [about](https://mmhaskell.com/blog/2017/9/4/deeper-still-convolutional-neural-networks) it.

**Comment by AdLucem** [comment]
Working on this, but with the fashion-mnist dataset (https://github.com/zalandoresearch/fashion-mnist).

**Comment by stites** [comment]
Looking forward to it!

**Comment by austinvhuang** [comment]
Closing this issue with https://github.com/hasktorch/hasktorch/pull/196
