### ISSUE TITLE
reference to -1 Word should be `subtract 1`

### ISSUE THREAD

**Issue by stites** [hasktorch/hasktorch#108]
From #106: This should be cleaned up:

```
src/Torch/Indef/Static/Tensor/Math/Pairwise.hs:53:18: warning: [-Woverflowed-literals]
    Literal -1 is out of the GHC.Word.Word8 range 0..255
   |
53 | v -^ t = v +^ ((-1) *^ t)
   |                  ^
```

**Comment by alexander-myltsev** [comment]
@stites I suppose this can be closed since it's fixed https://github.com/hasktorch/hasktorch/blob/244e8ccbe593a33246f06bae37ec1abae98fb7ae/indef/src/Torch/Indef/Static/Tensor/Math/Pairwise.hs#L60-L61

**Comment by stites** [comment]
Yes, this can be closed. Thank you @alexander-myltsev!
