### ISSUE TITLE
Make+OSX Install broken with stack-managed GHC

### ISSUE THREAD

**Issue by tonyday567** [hasktorch/hasktorch#148]
On a fresh clone of the repo, the first step of the install: `make init` (os x) gives me:

```
~/haskell 
# cd hasktorch/
~/haskell/hasktorch  master*
# make init
/bin/sh: ghc: command not found
GHC version detected 
Makefile:9: *** GHC version must be 8.4.2, 8.4.3, 8.4.4, or 8.6.1.  Stop.
~/haskell/hasktorch  master*
# which ghc
~/haskell/hasktorch  master*
# 

```

I don't have a global ghc.  Call me old school, but I'd rather have that managed by stack.

Any recommendations?

**Comment by tonyday567** [comment]
So running through Makefile, I just hardcoded the GHC version, and everything worked out.  Then I get:

```
# cabal new-run static-tensor-usage --flags=-cuda
Up to date
dyld: Library not loaded: @rpath/libATen.1.dylib
  Referenced from: /Users/tonyday/haskell/hasktorch/dist-newstyle/build/x86_64-osx/ghc-8.4.3/hasktorch-examples-0.0.1.0/x/static-tensor-usage/build/static-tensor-usage/static-tensor-usage
  Reason: image not found
Abort trap: 6
```

@rpath?  Not sure what this is,, I imagine something isn't picking up the aten directory?

**Comment by junjihashimoto** [comment]
Hi, 
We can not build hasktorch by stack, because backpack does not work on stack.
https://github.com/commercialhaskell/stack/issues/2540
(Let's improve stack.)

**Comment by junjihashimoto** [comment]
> dyld: Library not loaded: @rpath/libATen.1.dylib

This is because dyld does not find dynamic library.

See following commands. set DYLD_LIBRARY_PATH.
https://github.com/hasktorch/hasktorch/blob/master/setenv

**Comment by tonyday567** [comment]
The above issue was fixed with:

```
DYLD_LIBRARY_PATH="ffi/deps/aten/build/lib/" cabal new-run static-tensor-usage --flags=-cuda 
```

So, do I need to refer to the cabal.project.local in some way?  It looks like this:

```
extra-lib-dirs: /Users/tonyday/haskell/hasktorch/ffi/deps/aten/build/lib/

extra-include-dirs: /Users/tonyday/haskell/hasktorch/ffi/deps/aten/build/include/
extra-include-dirs: /Users/tonyday/haskell/hasktorch/ffi/deps/aten/build/include/TH
extra-include-dirs: /Users/tonyday/haskell/hasktorch/ffi/deps/aten/build/include/THNN
extra-include-dirs: /Users/tonyday/haskell/hasktorch/ffi/deps/aten/build/include/THC
extra-include-dirs: /Users/tonyday/haskell/hasktorch/ffi/deps/aten/build/include/THCUNN

package *
  flags: -cuda +lite

```

**Comment by tonyday567** [comment]
ok great, setenv did the trick.

**Comment by junjihashimoto** [comment]
> So, do I need to refer to the cabal.project.local in some way? 

yes.

**Comment by tonyday567** [comment]
The project is very close to supporting both stack and osx out of the box.
It feels like the “stack doesnt support backpack” issues can be readily worked around. 
Would there be interest in a PR to fix up ‘make int’ or is someone already on it?

**Comment by junjihashimoto** [comment]
I think if we use nix-shell which setups global ghc, we do not need to fix ‘make int’.

**Comment by austinvhuang** [comment]
Perhaps, but nix tends to be viewed as a substantial dependency to pull in. @tonyday567 would be happy to have a look at a PR. I'm curious what the workaround you have in mind looks like, definitely there'd be a lot of interest if building with stack were doable.

**Comment by tonyday567** [comment]
ok, will give it a go.

Personally. I built by just pointing to a stack-managed ghc version. I imagine that ‘cabal v2-build all’ can be wrapped by stack somehow, then its just a matter of adding a usestackghc flag and maybe passing a resolver to check the ghc version, find it in stack, and create a cabal freeze file.

So its not using stack instead of cabal, just avoiding a global ghc install.

**Comment by stites** [comment]
stack-linux, stack-OSX, and cabal-v2-linux are now in CI with a much simpler build process via #151 . The Makefile has also been removed. Please reopen if you come across any new build issues!
