### ISSUE TITLE
Nix support for hasktorch-0.2.0.0

### ISSUE THREAD

**Issue by stites** [hasktorch/hasktorch#152]
From #143:

> ffi-experimental is in master, and it doesn't actively support a nix workflow. [pytorch-world](https://github.com/stites/pytorch-world) (which I've renamed from "libtorch-nix") will be the best place to go to iterate on nix-support. It's also where I've been working on the [pytorch-1.1.0 derivation](https://github.com/NixOS/nixpkgs/pull/65041) -- which works without FBGEMM, and might turn into a 1.1.1 derivation.
>
> If you'd like to work on hasktorch with nix, please help out on that repo (which is properly pinned, following lorri's style). https://github.com/stites/pytorch-world/issues/2 blocks a cmake-less libtorch (which is nessecary for hasktorch), @tscholak has also been helping test that repo on darwin.
>
> If someone starts working on nix support and needs a pin, please pull in pytorch-world as a submodule in a `nix` folder (so `<hasktorch_root>/nix`) and use the pin located at `<hasktorch_root>/nix/pin`.
>
> Refer to https://github.com/stites/probtorch/tree/nix as an example.

This supercedes #103 given all of the latest changes to hasktorch.

**Comment by tscholak** [comment]
Sweet!  Great work @stites 
I’ve started working on nix support while 0.2 was still in separate in `ffi-experimental`. See my fork here: https://github.com/tscholak/ffi-experimental/tree/nix
There were some blockers with libtorch and c includes not being found.
I’m travelling right now, but I will get back to that eventually

**Comment by wavewave** [comment]
Development shell is configured :-) #162
