### ISSUE TITLE
Support for serialized models

### ISSUE THREAD

**Issue by o1lo01ol1o** [hasktorch/hasktorch#159]
Ola,
  Where could one look to figure out how to implement "serialization"?   My naive understanding of such an implementation would be something like: 
 
 - for any `torch` or `aten` datatype, rely on an `ffi` function (if such a thing exists) to get `bytestring` representations;

 - for Haskell datatypes, implement [`serialize`](http://hackage.haskell.org/package/serialise) instances that dumbly consider the above `torch`/`aten` representation to be a cannonical binary object representation.

Is the above generally correct?

**Comment by junjihashimoto** [comment]
Hi,
It is correct.
You can see the serialization from the below link.
https://github.com/hasktorch/hasktorch/blob/master/hasktorch/src/Torch/Tensor.hs#L144-L162

**Comment by o1lo01ol1o** [comment]
Ah, great.  So effectively 

```haskell
asTensor :: a -> Tensor
asValue :: Tensor -> a
-- where (Serialise a)
```
are all we need to serialize a `Parameter`.  Awsome.

**Comment by o1lo01ol1o** [comment]
@junjihashimoto  Is there a (recommended) way to determine the type of a `Tensor`?  In order to serialize an `[a]` I need to know what `a` is.  I see there's the `_dtype` function:  Is it appropriate to use it to reify an `a` from a `Tensorlike a`?

**Comment by junjihashimoto** [comment]
@o1lo01ol1o 
The recommendation to get the type a `Tensor` is using not `_dtype` function but `dtype` function.
`dtype` function returns `DType` including the types pytorch supports.
https://github.com/hasktorch/hasktorch/blob/master/hasktorch/src/Torch/Tensor.hs#L68-L69

`_dtype` function is for static typed tensor. It is to determine the `DType` of general type like Int, Float, Double and so on.

**Comment by tscholak** [comment]
is this resolved with https://github.com/hasktorch/hasktorch/pull/160 being merged?

**Comment by o1lo01ol1o** [comment]
@tscholak Really the example should serialize the `DType` with the parameter so that deserialization has access to the correct type, but I didn't have this information at merge.  will try to get to it a bit later

**Comment by junjihashimoto** [comment]
@o1lo01ol1o 
https://github.com/hasktorch/hasktorch/pull/230
This torch's serialization can deserialize the values with correct types.
So I will close this issue.
Please let me know if you have any questions.
