### ISSUE TITLE
Fix the test with ExitFailure (-9)

### ISSUE THREAD

**Issue by junjihashimoto** [hasktorch/hasktorch#178]
Sometimes CI fails with ExitFailure (-9) like [this link](https://circleci.com/gh/hasktorch/hasktorch/2047).
I want to fix the error.
I think the error happens by OOM.

**Comment by tscholak** [comment]
@junjihashimoto has this been resolved by your recent work on CI?

**Comment by junjihashimoto** [comment]
I think so.
I do not see OMM after starting github-actions.
