### ISSUE TITLE
libraries: libc10.so Cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by 524119574** [hasktorch/hasktorch#293]
When I am following the instruction to run the regression I got the error when I run:

`stack run regression`

and it complains about:
`hasktorch/.stack-work/install/x86_64-linux/e57d0afa7abbf44e537c5d4ed24d3e564303be076ac7c663c9dbbeb1b641e1c6/8.6.5/bin/regression: error while loading shared libraries: libc10.so: cannot open shared object file: No such file or directory`

So I have manually added the `hasktorch/deps/libtorch/lib` to `LD_LIBRARY_PATH` and then it works.

So my question is:

1. Does this also happen in other people's machine or it's just related to my system
2. Is this the correct steps to take when resolving this issue?

**Comment by junjihashimoto** [comment]
See https://github.com/hasktorch/hasktorch#getting-started.
Probably, you should setup libtorch and run "source setenv" to setup environment variables

**Comment by 524119574** [comment]
I see.
