### ISSUE TITLE
Guidance For Contribution to GSoC'20

### ISSUE THREAD

**Issue by SurajK7** [hasktorch/hasktorch#307]
Hi, I am a GSoC'20 aspirant looking to contribute to the Hasktorch library. I am particularly intrigued by the idea "Expand ecosystem around higher-level functionality" mentioned in the Ideas webpage. I would like to know how to get started for the same as I am highly motivated to contribute to Hasktorch library as a part of GSoC 2020. I have prior experience working with deep learning as highlighted in my [resume](https://surajk7.github.io/).
@junjihashimoto @austinvhuang

**Comment by junjihashimoto** [comment]
Welcome! Are you familiar with haskell and hasktorch?
If not so, I recommend to try to add typed function, because  you can learn the development process.
https://github.com/hasktorch/hasktorch/issues/233

**Comment by SurajK7** [comment]
Thanks for replying, as of now, I am not familiar with Haskell and hasktorch, 
 and as suggested I will start working on #233.
