### ISSUE TITLE
Improve compilation time

### ISSUE THREAD

**Issue by junjihashimoto** [hasktorch/hasktorch#373]
hasktorch's compilation takes long time, even if you have many cpu cores.
Because a single file like Native.hs has many functions.

There is a known way to speed up in the case.
https://www.parsonsmatt.org/2019/11/27/keeping_compilation_fast.html
However, the way is difficult to maintain with handwritten code.

We can make a program that generates code similar to the way.
autoexporter and hspec-discover have already had generators working at compile time.

https://hackage.haskell.org/package/autoexporter
http://hspec.github.io/hspec-discover.html

**Comment by tscholak** [comment]
I'd like us to address this soon. We should split `Native.hs` into several smaller modules, maybe one for each op

**Comment by junjihashimoto** [comment]
This is supported by this pr https://github.com/hasktorch/hasktorch/pull/419.
