### ISSUE TITLE
Readme refers to removed example

### ISSUE THREAD

**Issue by mcwitt** [hasktorch/hasktorch#398]
It looks like `examples/library-example` was removed in 5bd688e0bb46cc84361cc11ad361d6bf0e405573, but there is still a reference to it in the [readme](https://github.com/hasktorch/hasktorch#using-as-a-library-in-a-project-via-nix).

Should we remove the reference for now, and open an issue to add a similar example using the new `haskell.nix` infrastructure? (From my perspective as a newcomer this would be useful.)

**Comment by tscholak** [comment]
I'm on it. I just rewrote most of the README.md, see https://github.com/hasktorch/hasktorch/pull/392/files#diff-04c6e90faac2675aa89e2176d2eec7d8
