### ISSUE TITLE
Can only express subset of allowed offsets in `diagEmbed`, `diagflat`, `diagonal`

### ISSUE THREAD

**Issue by mcwitt** [hasktorch/hasktorch#416]
In `Torch.Functional`, [diagEmbed][], [diagflat][], and [diagonal][] each take a value of type [Offset][] to specify the desired diagonal; `Offset` has 3 values (`OffsetMain`, `OffsetAbove`, `OffsetBelow`).

On the other hand, the PyTorch interface (e.g. [diag_embed][]) allows an integer offset (i.e. diagonals other than -1, 0, 1).

In the same module, [diag][] is using the `Diag` wrapper around `Int`s. Maybe we should transition the others to this convention?

[diagEmbed]: https://github.com/hasktorch/hasktorch/blob/fa0e9c2d4d0d06228001b5bd317bb563ec6120ae/hasktorch/src/Torch/Functional.hs#L1245-L1251
[diagflat]: https://github.com/hasktorch/hasktorch/blob/fa0e9c2d4d0d06228001b5bd317bb563ec6120ae/hasktorch/src/Torch/Functional.hs#L1269-L1273
[diagonal]: https://github.com/hasktorch/hasktorch/blob/fa0e9c2d4d0d06228001b5bd317bb563ec6120ae/hasktorch/src/Torch/Functional.hs#L1277-L1284
[Offset]: https://github.com/hasktorch/hasktorch/blob/fa0e9c2d4d0d06228001b5bd317bb563ec6120ae/hasktorch/src/Torch/Functional.hs#L1253
[diag_embed]: https://pytorch.org/docs/stable/torch.html?highlight=diag_embed#torch.diag_embed
[diag]: https://github.com/hasktorch/hasktorch/blob/fa0e9c2d4d0d06228001b5bd317bb563ec6120ae/hasktorch/src/Torch/Functional.hs#L1238-L1242

**Comment by austinvhuang** [comment]
Hm I think the limitation to 3 values was a bug on my part - there are some function arguments where integers are used as flags for which a custom ADT wraps the flag for readability and preciseness. However this parameter isn't a flag so it should be changed to take integer arguments.

Happy to take a PR patch to fix this (o/w will try to find time later this week to submit one).

**Comment by mcwitt** [comment]
> Happy to take a PR patch to fix this (o/w will try to find time later this week to submit one).

I have some spare time for the next couple of days, so I might take a crack at a PR if you don't mind :)

I was also planning to add typed versions of these functions (#233), which was how I stumbled upon this in the first place.

**Comment by austinvhuang** [comment]
That would be great, thank you!
