### ISSUE TITLE
TensorLike for generic ADT

### ISSUE THREAD

**Issue by junjihashimoto** [hasktorch/hasktorch#423]
In some use-cases, each element of the array has a different meaning.
For example, in image detection, there is Box data-type below.
The first element is the X axis, the second element is the Y axis, and the third element is the width.
In order to automatically make this data a 4-dimensional tensor, I want to add generic type of TensorLike.

```Haskell
data Box = Box {
  x :: Float
, y :: Float
, w :: Float
, h :: Float
}
```

**Comment by tscholak** [comment]
that would be neat!

**Comment by junjihashimoto** [comment]
This feature is implemented by namedtensor.
https://github.com/hasktorch/hasktorch/pull/544
