### ISSUE TITLE
segfault when `asValue` is used on CUDA tensor

### ISSUE THREAD

**Issue by tscholak** [hasktorch/hasktorch#430]
```
> (asValue . toDynamic $ ones @'[3,2] @'Float @'( 'CUDA, 0)) :: [[Float]]
```
results in a `SIGSEGV`.

```
> toList . Just $ ones @'[3,2] @'Float @'( 'CUDA, 0)
[[1.0,1.0],[1.0,1.0],[1.0,1.0]]
```
does not.

**Comment by junjihashimoto** [comment]
Good point. 
It seems that `toList` is copied from cuda to cpu before `asValue`.
When we call asValue in CUDA, `SIGSEGV` may be thrown.

**Comment by junjihashimoto** [comment]
https://github.com/tycho01/synthesis/issues/31
This `SIGSEGV` problem may be caused by the same problem.

**Comment by junjihashimoto** [comment]
https://github.com/hasktorch/hasktorch/blob/master/hasktorch/src/Torch/Tensor.hs#L481-L485
This has already been fixed.
