### ISSUE TITLE
Quickjump does not work on https://hasktorch.github.io

### ISSUE THREAD

**Issue by junjihashimoto** [hasktorch/hasktorch#529]
We can't search the hasktorch APIs on hasktorch.org, because quickjump doesn't work.
![image](https://user-images.githubusercontent.com/2469618/109771673-6f2e7980-7c40-11eb-8e5f-ced56bae1d12.png)

**Comment by austinvhuang** [comment]
Darn, maybe we'll just link out to the docs instead of embedding them until we find a better solution.

**Comment by junjihashimoto** [comment]
iohk found the solution.
https://github.com/input-output-hk/cardano-node/blob/master/scripts/haddocs.sh#L97-L108

**Comment by junjihashimoto** [comment]
![image](https://user-images.githubusercontent.com/2469618/109915648-84191480-7cf5-11eb-9007-ef7a8adea8de.png)
The solution works.

**Comment by austinvhuang** [comment]
Thanks @junjihashimoto ! Works on hasktorch.org too now!
