### ISSUE TITLE
CUDA support running on WSL

### ISSUE THREAD

**Issue by Reep236** [hasktorch/hasktorch#535]
When attempting to run the MNIST example in a nix-shell on wsl, per the CUDA on WSL instructions from Nvidia 
[here](https://docs.nvidia.com/cuda/wsl-user-guide/index.html) and the directions for hasktorch on Nix with cabal and CUDA, I am encountering the error mentioned under known issues for moving the tensor to CUDA:0.

I confirmed CUDA was working on WSL with the example provided in the CUDA on WSL setup instructions, and I confirmed I could run the static-mnist-cnn on CPU. 

The instructions from here direct one as follows: 
```If that happens, check if /run/opengl-driver/lib exists. If not, make sure your CUDA drivers are installed correctly.``` 
Given that Nvidia specifically directs one not to install the actual drivers in WSL, only the toolkit as the beta driver and dev channel build of Windows support GPU paravirtualization with WSL2, that library does not exist. Will/does hasktorch have support for this form of CUDA in any way? 

If this method would not work, does anyone know of another way to get hasktorch running with CUDA support on WSL?

I tried with and without the mesa-utils package I saw mentioned elsewhere for openGL. This was also unsuccessful and I was left with the same error.

**Comment by junjihashimoto** [comment]
WSL's CUDA is not the same as nixos's one.
nixos cuda uses device files like /dev/nvidiactl, but WSL's one uses library files like /usr/lib/wsl/lib/libdxcore.so.

Could you add `LD_LIBRARY_PATH=/usr/lib/wsl/lib` before running `static-mnist-cnn`.

**Comment by Reep236** [comment]
This worked perfectly, thank you.
