### ISSUE TITLE
Incongruity between installation instructions and get-deps.sh

### ISSUE THREAD

**Issue by TomLippincott** [hasktorch/hasktorch#555]
The instructions involve cd/pushd into deps/ before invoking 'get-deps.sh', but that leads to:

```
You need to run this command from the toplevel of the working tree.
```

while running from the top-level directory, in addition to not placing the downloads under deps/, eventually errors out with:

```
./deps/get-deps.sh: line 212: pushd: ../spec: No such file or directory
```

**Comment by TomLippincott** [comment]
(it looks like all that needs to change is the git submodule invocation, which has to be at the top level)

**Comment by junjihashimoto** [comment]
@TomLippincott 
Could you try the current master branch?
Current branch does not have the comment like "You need to run".

**Comment by TomLippincott** [comment]
@junjihashimoto 
Ah, it looks like this is due to an old git version: starting with 1.8.4 it is no longer an issue.  Thanks!
