### ISSUE TITLE
Converting to ONNX

### ISSUE THREAD

**Issue by tom-huntington** [hasktorch/hasktorch#583]
https://github.com/hasktorch/hasktorch/blob/0da0b85fd402ecf80cc45f153f8a05e5eaf2347f/hasktorch/src/Torch/Script.hs#L435

Okay so I stole some code from https://github.com/hasktorch/hasktorch/blob/0da0b85fd402ecf80cc45f153f8a05e5eaf2347f/hasktorch/test/ScriptSpec.hs#L26 and managed to save a torchscript .pt file:

```
{-# LANGUAGE RecordWildCards #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE DeriveGeneric #-}
module Main where

import GHC.Generics
import Torch.NN
import Torch.Tensor
import Torch hiding (forward)
import Torch.Script


data MLPSpec = MLPSpec {
    inputFeatures :: Int,
    hiddenFeatures0 :: Int,
    hiddenFeatures1 :: Int,
    outputFeatures :: Int
    } deriving (Show, Eq)

data MLP = MLP {
    l0 :: Linear,
    l1 :: Linear,
    l2 :: Linear
    } deriving (Generic, Show)

instance Parameterized MLP
instance Randomizable MLPSpec MLP where
    sample MLPSpec {..} = MLP 
        <$> sample (LinearSpec inputFeatures hiddenFeatures0)
        <*> sample (LinearSpec hiddenFeatures0 hiddenFeatures1)
        <*> sample (LinearSpec hiddenFeatures1 outputFeatures)

mlp :: MLP -> Tensor -> Tensor
mlp MLP{..} input = 
    logSoftmax (Dim 1)
    . linear l2
    . relu
    . linear l1
    . relu
    . linear l0
    $ input

main :: IO ()
main = do
  v00 <- randnIO' [3,784] -- NOT SURE ABOUT THE 3 
  init' <- sample (MLPSpec 784 64 32 10)
  m <- traceWithParameters "MyModule" (\p [x] -> return [(mlp p x)]) init' [v00]
  sm <- toScriptModule m
  save sm "mlp.pt"
  print $ mlp init' (ones' [1,784])
```

However, when I load this model into python and try to export it to onnx
```
import torch
import torch.onnx as onnx

model = torch.jit.load('mlp.pt')
batch_size = 1
args = torch.rand(batch_size,784).cuda()
print(args)
model = model.cuda()
model.eval()
example_outputs = model(args)
print(example_outputs)
print(example_outputs.shape)
onnx.export(model,
    args,
    'model.onnx',
    export_params=True,
    verbose=True,
    example_outputs=example_outputs
  )
```

I am getting the error:
>AttributeError: 'RecursiveScriptModule' object has no attribute 'training'

Which came up on this github issue https://github.com/PeterL1n/BackgroundMattingV2/issues/93
>You should use the pytorch weights instead of the torchscript weights here.

However, I managed to get the code from this issue https://github.com/pytorch/pytorch/issues/33495 that exports from a torchscript model to work so torchscript models can be saved.

Does anyone know what's happening? Maybe I'll just use PyTorch

**Comment by austinvhuang** [comment]
You're welcome to use PyTorch, certainly model exports have been more widely tested. We aren't doing anything custom to haskell or hasktorch for tracing, we're just calling out to C++ libtorch's trace. In this case does example_outputs get displayed (to confirm the export is a valid torchscript IR)? 

Looking at the onnx export example:
https://pytorch.org/docs/stable/onnx.html#example-end-to-end-alexnet-from-pytorch-to-onnx

and based on the issue discussion you link recommending exporting direct from python, my guess is direct module-to-onnx export is more mature than taking a torchscript object as input. pytorch->torchscript->onnx seems to work, but maybe tracing from libtorch/C++ isn't as mature. Probably the way to confirm this is a small C++ test and file a libtorch issue if that's the case. @junjihashimoto any other thoughts?

**Comment by junjihashimoto** [comment]
Thank you for your trial.
pytorch's module has the attribute('training')  by default, on the other hand, traced module does not have it.
https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/module.py#L256

It seems that python sets the flag here.
https://github.com/pytorch/pytorch/blob/master/torch/jit/_trace.py#L1035

I think we can add the attribute('training') by libtorch's api.

c++ module  has not attributes but parameters. 
https://github.com/pytorch/pytorch/blob/master/torch/csrc/api/include/torch/nn/module.h

**Comment by junjihashimoto** [comment]
I'm interested in this trial and would like to integrate the conversion using python with this flow(https://github.com/hasktorch/hasktorch-datasets).

**Comment by tom-huntington** [comment]
> In this case does example_outputs get displayed (to confirm the export is a valid torchscript IR)?

Yes, example_outputs is a valid `[batch_size,10]` tensor as expected.

**Comment by tom-huntington** [comment]
I got it to work by converting the model to cuda (I updated the code above). It gives me this warning

>/home/a/.local/lib/python3.9/site-packages/torch/onnx/utils.py:341: UserWarning: Model has no forward function
  warnings.warn("Model has no forward function")

But the model seems to work in this code
```
import numpy
import onnxruntime as rt
import numpy.random

X_test = numpy.random.default_rng(42).random((1,784),dtype=numpy.single)
print(X_test)

sess = rt.InferenceSession("model.onnx")
input_name = sess.get_inputs()[0].name
print(sess)
print(input_name)
pred_onx = sess.run(None, {input_name: X_test})[0]
print(pred_onx)
```

I'll test again with the xor-mlp to make sure it's giving correct outputs.
