### ISSUE TITLE
remove `hspec-discover` from the project

### ISSUE THREAD

**Issue by tscholak** [hasktorch/hasktorch#586]
it doesn't work with nix and cabal.
if we get rid of it, we can finally set `exactDeps = true`.
see also https://github.com/input-output-hk/haskell.nix/issues/231#issuecomment-787932537

**Comment by junjihashimoto** [comment]
I'm not in trouble, but if someone is in trouble, we can delete it. Can the same be said for doctest?

**Comment by junjihashimoto** [comment]
```
$ git grep -in  hspec-di
.github/workflows/cabal-linux.yml:47:        cabal v2-install hspec-discover
.github/workflows/cabal-macos.yaml:46:        cabal v2-install hspec-discover
Dockerfile:19:RUN cabal v2-install hspec-discover
```
hspec-discover is no longer used.
