### ISSUE TITLE
Trouble using nix-shell 

### ISSUE THREAD

**Issue by offendo** [hasktorch/hasktorch#641]
Hello everyone,

I've never used nix before so apologies if the problem is basic. 

I'm running the nix-shell command from the README to make a shell with CUDA 11 support. 

```text
❯ nix-shell --arg cudaSupport true --argstr cudaMajorVersion 11
error: cannot evaluate a function that has an argument without a value ('hasktorchProject')

       Nix attempted to evaluate a function as a top level expression; in
       this case it must have its arguments supplied either by default
       values, or passed explicitly with '--arg' or '--argstr'. See
       https://nixos.org/manual/nix/stable/#ss-functions.

       at /home/offendo/src/hasktorch/shell.nix:3:3:

            2| , cudaMajorVersion
            3| , hasktorchProject
             |   ^
            4| , torch

```

I tried adding `--argstr hasktorchProject test` just to see what happens, and then it complains about the next argument in the list.

I assume there's supposed to be arguments for each of the parameters, but I don't know what to give. Any help would be appreciated.

**Comment by junjihashimoto** [comment]
Hi,
Sorry for not updating README.
Could you take a look at this PR(https://github.com/hasktorch/hasktorch/pull/642/files), and try `nix develop` command?

**Comment by offendo** [comment]
I had to use the following command instead of `nix develop`, but then it worked!

```sh
nix --extra-experimental-features flakes  --extra-experimental-features nix-command develop
```
