### ISSUE TITLE
Issues with `stack ghci` and HLS

### ISSUE THREAD

**Issue by reubenharry** [hasktorch/hasktorch#652]
I'm having trouble getting HLS to run with the project. In VSCode, it simply reports a crash. Actually, even `stack ghci` gives:

GHCi, version 9.2.4: https://www.haskell.org/ghc/  :? for help
<command line>: cannot satisfy -package z-examples-z-static-mnist
    (use -v for more information)

Should I expect HLS and `stack ghci` to run out of the box?

p.s. This is an amazing project btw, excited to use it!

**Comment by junjihashimoto** [comment]
`stack ghci` should work. It is a stack's issue.
The issue of HLS may be ABI mismatch. 
The rebuild of HLS takes long time. 
https://discourse.nixos.org/t/ghc-abi-mismatch-for-hls-when-using-ghc942/23007

In my use case, I use some different ghc compilers, so I do not use HLS.

**Comment by junjihashimoto** [comment]
Is this issue the same as https://github.com/commercialhaskell/stack/issues/4616 ?
