### ISSUE TITLE
Libtorch-ffi doesn't compile on macOS

### ISSUE THREAD

**Issue by youqad** [hasktorch/hasktorch#654]
Hi, thank you for Hasktorch!
 
I'm a beginner, so my apologies if I'm posting it in the wrong place: as said in the title, following the instructions of https://github.com/hasktorch/hasktorch-stack-skeleton with the latest commit, on macOS Ventura 13.0.1 with ghc 9.2.4, the libtorch-ffi library doesn't compile on my machine. I suspect the source of the problem is here:

https://github.com/hasktorch/hasktorch/commit/4ab08a2962d4cac90f3ece4fe03320c63a8d6b72#r91693846

**Comment by junjihashimoto** [comment]
Hi, I think you need this patch (https://github.com/hasktorch/hasktorch-stack-skeleton/pull/4) .
After testing the patch, I'll update the skeleton to support ghc-9.2.

**Comment by junjihashimoto** [comment]
The patch has been merged.

**Comment by youqad** [comment]
Thank you @junjihashimoto , it works! 🎉
