### ISSUE TITLE
How can I use hasktorch as a library through haskell.nix?

### ISSUE THREAD

**Issue by jjdosa** [hasktorch/hasktorch#671]
I would like to create a Nix flake that utilizes `hasktorch` as an external library but has encountered difficulties while attempting to build it using the Haskell infrastructure in nixpkgs. Then I realized that `hasktorch` is packaged using `haskell.nix`, as I am not familiar with using `haskell.nix`, I am seeking guidance on how to integrate `hasktorch` into my project with `haskell.nix`. Below is an example scaffolding of Haskell package using `haskell.nix`, and added hasktorch as one of the inputs. Now what should I do to make the helloProject recognize `hasktorch` as an installed library?

```nix
{
  description = "A very basic flake";
  inputs.haskellNix.url = "github:input-output-hk/haskell.nix";
  inputs.nixpkgs.follows = "haskellNix/nixpkgs-unstable";
  inputs.flake-utils.url = "github:numtide/flake-utils";
  inputs.hasktorch.url = "github:hasktorch/hasktorch"; # I've added this
  outputs = { self, nixpkgs, flake-utils, haskellNix }:
    flake-utils.lib.eachSystem [ "x86_64-linux" "x86_64-darwin" ] (system:
    let
      overlays = [ haskellNix.overlay
        (final: prev: {
          # This overlay adds our project to pkgs
          helloProject =
            final.haskell-nix.project' {
              src = ./.;
              compiler-nix-name = "ghc925";
              # This is used by `nix develop .` to open a shell for use with
              # `cabal`, `hlint` and `haskell-language-server`
              shell.tools = {
                cabal = {};
                hlint = {};
                haskell-language-server = {};
              };
              # Non-Haskell shell tools go here
              shell.buildInputs = with pkgs; [
                nixpkgs-fmt
              ];
              # This adds `js-unknown-ghcjs-cabal` to the shell.
              # shell.crossPlatforms = p: [p.ghcjs];
            };
        })
      ];
      pkgs = import nixpkgs { inherit system overlays; inherit (haskellNix) config; };
      flake = pkgs.helloProject.flake {
        # This adds support for `nix build .#js-unknown-ghcjs:hello:exe:hello`
        # crossPlatforms = p: [p.ghcjs];
      };
    in flake // {
      # Built by `nix build .`
      packages.default = flake.packages."hello:exe:hello";
    });
}
```

Another issue I have is that after adding `hasktorch` into the inputs, I am having this error:
```sh
error: cannot fetch input 'path:./nix-tools?lastModified=1&narHash=sha256-pqNsBhQkO%2fnT991ASoSXsn07P7lNqpTP0wIV85wft30=' because it uses a relative path
```

**Comment by junjihashimoto** [comment]
@jjdosa Hi, hasktorch-skeleton provides such an initial project. Is it helpful?
https://github.com/hasktorch/hasktorch-skeleton/blob/master/flake.nix

**Comment by jjdosa** [comment]
@junjihashimoto Thank you for guiding me to exactly what I was looking for! After reviewing the skeleton repository, I noticed that the `cabal.project` file contains the dependencies `hasktorch` and `libtorch-ffi`. This is different from adding Haskell packages to the `haskellPackages` attribute set using the overlay mechanism that I'm familiar with.

As the ghc version that my team and I use mostly is 9.2.4, I spent some time to bump up the ghc version from 8.10.4 to 9.2.4. To do that I had to update hasktorch to the lastest master (7b63d730964a44a6bcdd853cd5b140a24e210298) and other related packages that are in the cabal.project of hasktorch. Although I was able to upgrade successfully, I believe there may be a better method to accomplish this. Personally, I think that it would be better if I could retrieve all of Hasktorch's dependencies through a flake input, possibly by a single mechanism such as an overlay.

I have created a fork for the update, which can be found at https://github.com/haedosa/hasktorch-skeleton. However, I must mention that I am not familiar with stack, and as such, have not made any changes to the `stack.yaml` file or related components. Furthermore, I want to clarify that although I have confirmed the skeleton builds successfully for GHC versions 9.2.4, 9.2.7, and 9.2.8, I have not tested its runtime functionality for Hasktorch yet.

**Comment by junjihashimoto** [comment]
@jjdosa Hi, we have another stack's skeleton (https://github.com/hasktorch/hasktorch-stack-skeleton). 
So if the updated skeleton is available, I can merge it.

**Comment by jjdosa** [comment]
@junjihashimoto Apologies for the delay. I was busy with a project that had a deadline last Friday. I have removed the stack and niv-related configurations from the repository at https://github.com/haedosa/hasktorch-skeleton/commit/60c34a4a17804a6373bc6205873a839a56791cb3. If you'd like me to create a pull request (PR) with those changes, please let me know.

Additionally, my friend, @jhhuh created a repository at https://github.com/asgard-labs/hasktorch-nix, where hasktorch and related packages are included in the Haskell package set in Nix through the flake inputs. Building on that, I have added the `hasktorch-nix-skeleton` repository at https://github.com/haedosa/hasktorch-nix-skeleton. I hope it serves as an example of how to use hasktorch with Nix, without relying on haskell-nix.

**Comment by jhhuh** [comment]
Just to be clear, the repo @jjdosa mentioned is a direct translation of what's done here but only for `cudaSupport = false` and `system = "x86_64-linux"`. I just wanted to have a quick check if it is buildable without IOHK infra. I will be soon adding the other options, but it is as it is at least for now.

Anyway, thanks for developing a great library. Kudos.
