### ISSUE TITLE
GHC-9.6.2 support

### ISSUE THREAD

**Issue by Dessix** [hasktorch/hasktorch#673]
With the recent [release of GHC 9.6.2](https://www.haskell.org/ghc/blog/20230523-ghc-9.6.2-released.html) and HLS's 9.6 support nearing, I wanted to prepare a tracking item for support for the latest GHC.

[HLS 9.6.2 support (tracking item)](/haskell/haskell-language-server/pull/3608) is set to arrive with their release of version `2.0.0.1`, and is - hopefully - the largest remaining blocker to supporting (but not necessarily utilizing) the newer record update functionalities with regard to GADTs and existentials.

While these have significant potential for expressiveness on tensor semantics, they offer developer quality-of-life improvements in the rest of the program's structure, so I've been following this release closely, and believe it's worth targeting for HaskTorch support in the near future.

**Comment by junjihashimoto** [comment]
The master branch currently supports GHC 9.6.
