### ISSUE TITLE
Building with cabal chokes on a commit sha from cabal.project

### ISSUE THREAD

**Issue by andreasabel** [hasktorch/hasktorch#678]
```
$ cabal build -w ghc-9.2.8
fatal: Could not parse object '2d0fe9b2f0aa0e1aefc7bfed95a501e59486afb0'.
```
This is the `tag` from these source repos:
https://github.com/hasktorch/hasktorch/blob/7b63d730964a44a6bcdd853cd5b140a24e210298/cabal.project#L28-L40

**Comment by junjihashimoto** [comment]
I think that inline-c's master is rebased, so the tag is removed.
This pr uses hackage's inline directly. It contains necessary bug fixes.
I'm a maintainer of inline-c, so this kind of issue will go away.
https://github.com/hasktorch/hasktorch/issues/678

**Comment by junjihashimoto** [comment]
@andreasabel Thx!

**Comment by andreasabel** [comment]
Thanks for the quick solution!  Works for me now.
