### ISSUE TITLE
Link error on macos(xcode/clang) : Duplicate symbol error for libtorch-ffi.

### ISSUE THREAD

**Issue by junjihashimoto** [hasktorch/hasktorch#708]
Linking fails on MacOS (xcode/clang) due to an error caused by duplicate symbols.

```
[104 of 105] Compiling Torch.Internal.Unmanaged.Type.Tuple ( src/Torch/Internal/Unmanaged/Type/Tuple.hs, /Users/junji.hashimoto/git/hasktorch/dist-newstyle/build/aarch64-osx/ghc-9.6.3/libtorch-ffi-2.0.0.0/build/Torch/Internal/Unmanaged/Type/Tuple.o, /Users/junji.hashimoto/git/hasktorch/dist-newstyle/build/aarch64-osx/ghc-9.6.3/libtorch-ffi-2.0.0.0/build/Torch/Internal/Unmanaged/Type/Tuple.dyn_o )
ld: warning: -single_module is obsolete
ld: warning: search path '/Users/junji.hashimoto/git/hasktorch/deps/mklml/lib' not found
ld: warning: search path '/Users/junji.hashimoto/git/hasktorch/deps/libtorch/lib' not found
ld: warning: search path '/Users/junji.hashimoto/git/hasktorch/deps/libtokenizers/lib' not found
[105 of 105] Compiling Torch.Internal.Managed.Type.Tuple ( src/Torch/Internal/Managed/Type/Tuple.hs, /Users/junji.hashimoto/git/hasktorch/dist-newstyle/build/aarch64-osx/ghc-9.6.3/libtorch-ffi-2.0.0.0/build/Torch/Internal/Managed/Type/Tuple.o, /Users/junji.hashimoto/git/hasktorch/dist-newstyle/build/aarch64-osx/ghc-9.6.3/libtorch-ffi-2.0.0.0/build/Torch/Internal/Managed/Type/Tuple.dyn_o )
ld: warning: -single_module is obsolete
ld: warning: ignoring duplicate libraries: '-lc++'
ld: warning: search path '/Users/junji.hashimoto/git/hasktorch/deps/mklml/lib' not found
ld: warning: search path '/Users/junji.hashimoto/git/hasktorch/deps/libtorch/lib' not found
ld: warning: search path '/Users/junji.hashimoto/git/hasktorch/deps/libtokenizers/lib' not found
duplicate symbol '__ZTVN3c1020intrusive_ptr_targetE' in:
    /Users/junji.hashimoto/git/hasktorch/dist-newstyle/build/aarch64-osx/ghc-9.6.3/libtorch-ffi-2.0.0.0/build/Torch/Internal/Unmanaged/Type/C10Dict.dyn_o
    /Users/junji.hashimoto/git/hasktorch/dist-newstyle/build/aarch64-osx/ghc-9.6.3/libtorch-ffi-2.0.0.0/build/Torch/Internal/Unmanaged/Type/C10List.dyn_o
duplicate symbol '__ZTVN3c1015VariableVersion14VersionCounterE' in:
    /Users/junji.hashimoto/git/hasktorch/dist-newstyle/build/aarch64-osx/ghc-9.6.3/libtorch-ffi-2.0.0.0/build/Torch/Internal/Unmanaged/Type/Extra.dyn_o
    /Users/junji.hashimoto/git/hasktorch/dist-newstyle/build/aarch64-osx/ghc-9.6.3/libtorch-ffi-2.0.0.0/build/Torch/Internal/Unmanaged/Autograd.dyn_o
    /Users/junji.hashimoto/git/hasktorch/dist-newstyle/build/aarch64-osx/ghc-9.6.3/libtorch-ffi-2.0.0.0/build/Torch/Internal/Unmanaged/Optim.dyn_o
    /Users/junji.hashimoto/git/hasktorch/dist-newstyle/build/aarch64-osx/ghc-9.6.3/libtorch-ffi-2.0.0.0/build/Torch/Internal/Unmanaged/TensorFactories.dyn_o
ld: 2 duplicate symbols
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`gcc' failed in phase `Linker'. (Exit code: 1)
Error: cabal: Failed to build libtorch-ffi-2.0.0.0 (which is required by
test:spec from libtorch-ffi-2.0.0.0, exe:two-layer-network from
gradually-typed-examples-0.2.0.0 and others).
$ gcc --version
Apple clang version 15.0.0 (clang-1500.3.9.4)
Target: arm64-apple-darwin23.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by mlier** [comment]
`libtorch-ffi           > [105 of 105] Compiling Torch.Internal.Managed.Type.Tuple
libtorch-ffi           > ld: warning: search path '/Users/loysmasquelier1/CloudStation/donnee/devEdf/Haskell/hasktorch/deps/mklml/lib' not found
libtorch-ffi           > ld: warning: ignoring file '/Users/loysmasquelier1/CloudStation/donnee/devEdf/Haskell/hasktorch/deps/libtorch/lib/libc10.dylib': found architecture 'x86_64', required architecture 'arm64'
libtorch-ffi           > ld: warning: ignoring file '/Users/loysmasquelier1/CloudStation/donnee/devEdf/Haskell/hasktorch/deps/libtorch/lib/libtorch.dylib': found architecture 'x86_64', required architecture 'arm64'
libtorch-ffi           > ld: warning: ignoring file '/Users/loysmasquelier1/CloudStation/donnee/devEdf/Haskell/hasktorch/deps/libtorch/lib/libtorch_cpu.dylib': found architecture 'x86_64', required architecture 'arm64'
libtorch-ffi           > duplicate symbol '__ZTVN3c1020intrusive_ptr_targetE' in:
libtorch-ffi           >     /Users/loysmasquelier1/CloudStation/donnee/devEdf/Haskell/hasktorch/libtorch-ffi/.stack-work/dist/aarch64-osx/ghc-9.6.5/build/Torch/Internal/Unmanaged/Type/C10Dict.dyn_o
libtorch-ffi           >     /Users/loysmasquelier1/CloudStation/donnee/devEdf/Haskell/hasktorch/libtorch-ffi/.stack-work/dist/aarch64-osx/ghc-9.6.5/build/Torch/Internal/Unmanaged/Type/C10List.dyn_o
libtorch-ffi           > duplicate symbol '__ZTVN3c1015VariableVersion14VersionCounterE' in:
libtorch-ffi           >     /Users/loysmasquelier1/CloudStation/donnee/devEdf/Haskell/hasktorch/libtorch-ffi/.stack-work/dist/aarch64-osx/ghc-9.6.5/build/Torch/Internal/Unmanaged/Type/Extra.dyn_o
libtorch-ffi           >     /Users/loysmasquelier1/CloudStation/donnee/devEdf/Haskell/hasktorch/libtorch-ffi/.stack-work/dist/aarch64-osx/ghc-9.6.5/build/Torch/Internal/Unmanaged/Autograd.dyn_o
libtorch-ffi           >     /Users/loysmasquelier1/CloudStation/donnee/devEdf/Haskell/hasktorch/libtorch-ffi/.stack-work/dist/aarch64-osx/ghc-9.6.5/build/Torch/Internal/Unmanaged/Optim.dyn_o
libtorch-ffi           >     /Users/loysmasquelier1/CloudStation/donnee/devEdf/Haskell/hasktorch/libtorch-ffi/.stack-work/dist/aarch64-osx/ghc-9.6.5/build/Torch/Internal/Unmanaged/TensorFactories.dyn_o
libtorch-ffi           > ld: 2 duplicate symbols
libtorch-ffi           > clang: error: linker command failed with exit code 1 (use -v to see invocation)
libtorch-ffi           > `gcc' failed in phase `Linker'. (Exit code: 1)
Progress 65/71

Error: [S-7282]
       Stack failed to execute the build plan.

       While executing the build plan, Stack encountered the error:

       [S-7011]
       While building package libtorch-ffi-2.0.0.0 (scroll up to its section to see the error) using:
       /Users/loysmasquelier1/.stack/setup-exe-cache/aarch64-osx/Cabal-simple_6HauvNHV_3.10.3.0_ghc-9.6.5 --verbose=1 --builddir=.stack-work/dist/aarch64-osx/ghc-9.6.5 build lib:libtorch-ffi --ghc-options " -fdiagnostics-color=always"
       Process exited with code: ExitFailure 1`

`gcc --version
Apple clang version 15.0.0 (clang-1500.3.9.4)
Target: arm64-apple-darwin23.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin`

**Comment by junjihashimoto** [comment]
It seems that `-ld_classic` can solve it.

**Comment by junjihashimoto** [comment]
https://github.com/hasktorch/hasktorch/pull/698 fixes this issue.
