### ISSUE TITLE
Haskell implementation of optim package

### ISSUE THREAD

**Issue by stites** [hasktorch/hasktorch#80]
https://github.com/torch/optim/blob/master/doc/algos.md

**Comment by stites** [comment]
Note: https://github.com/mstksg/opto by @mstksg already exists

**Comment by austinvhuang** [comment]
Will need to revive this for the 0.2 release . https://github.com/hasktorch/hasktorch/pull/185 started some steps, but more needs to be done to get this library-ready.

I think this is a big enough task to split into smaller issues so I'm going to close this and create some smaller issues covering:

- Define and implement the library version of the interface
- Add tests to CI for each optimizer
- Implement a typed tensor counterpart
