### ISSUE TITLE
Break dependency on GHC-8.4 for release

### ISSUE THREAD

**Issue by stites** [hasktorch/hasktorch#98]
I believe this dependency comes from `singletons-2.4.0`, which we actually use very little of. There was a soft attempt at backwards compatibility in [`Torch/Indef/Static/Tensor.hs`](https://github.com/hasktorch/hasktorch/blob/master/indef/src/Torch/Indef/Static/Tensor.hs#L407) -- this needs to be more pervasive if we want to release hasktorch to hackage (which only does [builds up to 8.2.2](https://matrix.hackage.haskell.org/package/gym-http-api)) and stackage (if we want it in an lts like 11).

Breaking the dependency on ghc-8.4 stops the dependency on the [mstksg/type-combinators#ghc-8.4](https://github.com/mstksg/type-combinators/tree/ghc-8.4) git submodule and frees us from https://github.com/kylcarte/type-combinators/pull/9.

**Comment by mitchellwrosen** [comment]
Unfortunately 8.2 + backpack = broken, so I believe we need a new `type-combinators` to appear on Hackage.

**Comment by stites** [comment]
(adding issue reference): https://github.com/haskell/cabal/issues/4908

Stackage lts-11 is on 8.2.2 and the fix is only in 8.2.1 and ghc-HEAD.

Looks like we have to play the waiting game...

<br/>
<br/>

<img src="https://i.imgur.com/uBWeo5M.jpg" width="300px" height="100%">
